<Project>
    <PropertyGroup>
        <Nullable>enable</Nullable>
        <TargetFramework>net10.0</TargetFramework>
        <Company>CAPCOM CO., LTD.</Company>
        <Copyright>© CAPCOM CO., LTD. ALL RIGHTS RESERVED.</Copyright>
        <Authors>CAPCOM CO., LTD.</Authors>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

</Project>