<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>REDox.Toml</RootNamespace>
        <Title>$(AssemblyName)</Title>
        <Description>TOML parser/writer with comment-aware token DOM integration</Description>
        <PackageId>CAPCOM.$(AssemblyName)</PackageId>
        <PackageTags>$(PackageTags);toml;parser;config</PackageTags>
        <Version>$(VersionPrefix)-preview</Version>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\REDox\REDox.csproj" />
    </ItemGroup>
</Project>
